---
- name: Your First Custom Module
  hosts: localhost
  gather_facts: false
  connection: local
 
  tasks:
    - name: Show Version
      action: custom_module_1
      register: output

    - debug:
        var: output
